### ISSUE TITLE
Throw an HTTPError instead of RuntimeError

### ISSUE THREAD

**Issue by nilpunning** [Zoominfo/api-auth-python-client#4]
On these lines an exception is thrown using only the response text.  The very important status code is not included in that exception.  This makes it hard to debug why the request to ZoomInfo failed.

https://github.com/Zoominfo/api-auth-python-client/blob/1e4ecd4c466979da32277923b281305468fbc20c/zi_api_auth_client/zi_api_auth_client.py#L26-L27

https://github.com/Zoominfo/api-auth-python-client/blob/1e4ecd4c466979da32277923b281305468fbc20c/zi_api_auth_client/zi_api_auth_client.py#L37-L38

It would be better to do:

```
response.raise_for_status()
```

Requests library will throw an HTTPError which captures the status code and and URL which will better help people to determine what configuration is wrong.

**Comment by singh-harsh** [comment]
This response status is fixed in v20.0.0
